// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: market.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMarket = `-- name: CreateMarket :one
INSERT INTO markets (
    creator_id, title, course_code, exam_name, exam_date,
    prior_average, b, closes_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, creator_id, title, course_code, exam_name, exam_date, prior_average, b, shares_higher, shares_lower, status, outcome, closes_at, resolved_at, created_at, updated_at
`

type CreateMarketParams struct {
	CreatorID    uuid.UUID          `json:"creator_id"`
	Title        string             `json:"title"`
	CourseCode   string             `json:"course_code"`
	ExamName     string             `json:"exam_name"`
	ExamDate     pgtype.Date        `json:"exam_date"`
	PriorAverage int64              `json:"prior_average"`
	B            int64              `json:"b"`
	ClosesAt     pgtype.Timestamptz `json:"closes_at"`
}

func (q *Queries) CreateMarket(ctx context.Context, arg CreateMarketParams) (Market, error) {
	row := q.db.QueryRow(ctx, createMarket,
		arg.CreatorID,
		arg.Title,
		arg.CourseCode,
		arg.ExamName,
		arg.ExamDate,
		arg.PriorAverage,
		arg.B,
		arg.ClosesAt,
	)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.CourseCode,
		&i.ExamName,
		&i.ExamDate,
		&i.PriorAverage,
		&i.B,
		&i.SharesHigher,
		&i.SharesLower,
		&i.Status,
		&i.Outcome,
		&i.ClosesAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMarket = `-- name: DeleteMarket :exec
DELETE FROM markets
WHERE id = $1
`

func (q *Queries) DeleteMarket(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMarket, id)
	return err
}

const getMarketByID = `-- name: GetMarketByID :one
SELECT id, creator_id, title, course_code, exam_name, exam_date, prior_average, b, shares_higher, shares_lower, status, outcome, closes_at, resolved_at, created_at, updated_at FROM markets
WHERE id = $1
`

func (q *Queries) GetMarketByID(ctx context.Context, id uuid.UUID) (Market, error) {
	row := q.db.QueryRow(ctx, getMarketByID, id)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.CourseCode,
		&i.ExamName,
		&i.ExamDate,
		&i.PriorAverage,
		&i.B,
		&i.SharesHigher,
		&i.SharesLower,
		&i.Status,
		&i.Outcome,
		&i.ClosesAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMarkets = `-- name: ListMarkets :many
SELECT id, creator_id, title, course_code, exam_name, exam_date, prior_average, b, shares_higher, shares_lower, status, outcome, closes_at, resolved_at, created_at, updated_at FROM markets
ORDER BY created_at DESC
`

func (q *Queries) ListMarkets(ctx context.Context) ([]Market, error) {
	rows, err := q.db.Query(ctx, listMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Market
	for rows.Next() {
		var i Market
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.CourseCode,
			&i.ExamName,
			&i.ExamDate,
			&i.PriorAverage,
			&i.B,
			&i.SharesHigher,
			&i.SharesLower,
			&i.Status,
			&i.Outcome,
			&i.ClosesAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsByCourse = `-- name: ListMarketsByCourse :many
SELECT id, creator_id, title, course_code, exam_name, exam_date, prior_average, b, shares_higher, shares_lower, status, outcome, closes_at, resolved_at, created_at, updated_at FROM markets
WHERE course_code = $1
ORDER BY closes_at ASC
`

func (q *Queries) ListMarketsByCourse(ctx context.Context, courseCode string) ([]Market, error) {
	rows, err := q.db.Query(ctx, listMarketsByCourse, courseCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Market
	for rows.Next() {
		var i Market
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.CourseCode,
			&i.ExamName,
			&i.ExamDate,
			&i.PriorAverage,
			&i.B,
			&i.SharesHigher,
			&i.SharesLower,
			&i.Status,
			&i.Outcome,
			&i.ClosesAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsByCreator = `-- name: ListMarketsByCreator :many
SELECT id, creator_id, title, course_code, exam_name, exam_date, prior_average, b, shares_higher, shares_lower, status, outcome, closes_at, resolved_at, created_at, updated_at FROM markets
WHERE creator_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMarketsByCreator(ctx context.Context, creatorID uuid.UUID) ([]Market, error) {
	rows, err := q.db.Query(ctx, listMarketsByCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Market
	for rows.Next() {
		var i Market
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.CourseCode,
			&i.ExamName,
			&i.ExamDate,
			&i.PriorAverage,
			&i.B,
			&i.SharesHigher,
			&i.SharesLower,
			&i.Status,
			&i.Outcome,
			&i.ClosesAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsByStatus = `-- name: ListMarketsByStatus :many
SELECT id, creator_id, title, course_code, exam_name, exam_date, prior_average, b, shares_higher, shares_lower, status, outcome, closes_at, resolved_at, created_at, updated_at FROM markets
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMarketsByStatus(ctx context.Context, status MarketStatus) ([]Market, error) {
	rows, err := q.db.Query(ctx, listMarketsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Market
	for rows.Next() {
		var i Market
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.CourseCode,
			&i.ExamName,
			&i.ExamDate,
			&i.PriorAverage,
			&i.B,
			&i.SharesHigher,
			&i.SharesLower,
			&i.Status,
			&i.Outcome,
			&i.ClosesAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMarkets = `-- name: ListOpenMarkets :many
SELECT id, creator_id, title, course_code, exam_name, exam_date, prior_average, b, shares_higher, shares_lower, status, outcome, closes_at, resolved_at, created_at, updated_at FROM markets
WHERE status = 'open'
  AND closes_at > NOW()
ORDER BY closes_at ASC
`

func (q *Queries) ListOpenMarkets(ctx context.Context) ([]Market, error) {
	rows, err := q.db.Query(ctx, listOpenMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Market
	for rows.Next() {
		var i Market
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.CourseCode,
			&i.ExamName,
			&i.ExamDate,
			&i.PriorAverage,
			&i.B,
			&i.SharesHigher,
			&i.SharesLower,
			&i.Status,
			&i.Outcome,
			&i.ClosesAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMarket = `-- name: ResolveMarket :one
UPDATE markets
SET status  = 'resolved',
    outcome = $2
WHERE id = $1
RETURNING id, creator_id, title, course_code, exam_name, exam_date, prior_average, b, shares_higher, shares_lower, status, outcome, closes_at, resolved_at, created_at, updated_at
`

type ResolveMarketParams struct {
	ID      uuid.UUID         `json:"id"`
	Outcome NullMarketOutcome `json:"outcome"`
}

func (q *Queries) ResolveMarket(ctx context.Context, arg ResolveMarketParams) (Market, error) {
	row := q.db.QueryRow(ctx, resolveMarket, arg.ID, arg.Outcome)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.CourseCode,
		&i.ExamName,
		&i.ExamDate,
		&i.PriorAverage,
		&i.B,
		&i.SharesHigher,
		&i.SharesLower,
		&i.Status,
		&i.Outcome,
		&i.ClosesAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMarketShares = `-- name: UpdateMarketShares :one
UPDATE markets
SET shares_higher = $2,
    shares_lower  = $3
WHERE id = $1
RETURNING id, creator_id, title, course_code, exam_name, exam_date, prior_average, b, shares_higher, shares_lower, status, outcome, closes_at, resolved_at, created_at, updated_at
`

type UpdateMarketSharesParams struct {
	ID           uuid.UUID `json:"id"`
	SharesHigher int64     `json:"shares_higher"`
	SharesLower  int64     `json:"shares_lower"`
}

func (q *Queries) UpdateMarketShares(ctx context.Context, arg UpdateMarketSharesParams) (Market, error) {
	row := q.db.QueryRow(ctx, updateMarketShares, arg.ID, arg.SharesHigher, arg.SharesLower)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.CourseCode,
		&i.ExamName,
		&i.ExamDate,
		&i.PriorAverage,
		&i.B,
		&i.SharesHigher,
		&i.SharesLower,
		&i.Status,
		&i.Outcome,
		&i.ClosesAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMarketStatus = `-- name: UpdateMarketStatus :one
UPDATE markets
SET status = $2
WHERE id = $1
RETURNING id, creator_id, title, course_code, exam_name, exam_date, prior_average, b, shares_higher, shares_lower, status, outcome, closes_at, resolved_at, created_at, updated_at
`

type UpdateMarketStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status MarketStatus `json:"status"`
}

func (q *Queries) UpdateMarketStatus(ctx context.Context, arg UpdateMarketStatusParams) (Market, error) {
	row := q.db.QueryRow(ctx, updateMarketStatus, arg.ID, arg.Status)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.CourseCode,
		&i.ExamName,
		&i.ExamDate,
		&i.PriorAverage,
		&i.B,
		&i.SharesHigher,
		&i.SharesLower,
		&i.Status,
		&i.Outcome,
		&i.ClosesAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
