// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MarketOutcome string

const (
	MarketOutcomeHigher MarketOutcome = "higher"
	MarketOutcomeLower  MarketOutcome = "lower"
)

func (e *MarketOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MarketOutcome(s)
	case string:
		*e = MarketOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for MarketOutcome: %T", src)
	}
	return nil
}

type NullMarketOutcome struct {
	MarketOutcome MarketOutcome `json:"market_outcome"`
	Valid         bool          `json:"valid"` // Valid is true if MarketOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMarketOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.MarketOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MarketOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMarketOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MarketOutcome), nil
}

type MarketStatus string

const (
	MarketStatusOpen        MarketStatus = "open"
	MarketStatusClosed      MarketStatus = "closed"
	MarketStatusUnderReview MarketStatus = "under_review"
	MarketStatusResolved    MarketStatus = "resolved"
	MarketStatusCancelled   MarketStatus = "cancelled"
)

func (e *MarketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MarketStatus(s)
	case string:
		*e = MarketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MarketStatus: %T", src)
	}
	return nil
}

type NullMarketStatus struct {
	MarketStatus MarketStatus `json:"market_status"`
	Valid        bool         `json:"valid"` // Valid is true if MarketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMarketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MarketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MarketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMarketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MarketStatus), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Market struct {
	ID           uuid.UUID          `json:"id"`
	CreatorID    uuid.UUID          `json:"creator_id"`
	Title        string             `json:"title"`
	CourseCode   string             `json:"course_code"`
	ExamName     string             `json:"exam_name"`
	ExamDate     pgtype.Date        `json:"exam_date"`
	PriorAverage int64              `json:"prior_average"`
	B            int64              `json:"b"`
	SharesHigher int64              `json:"shares_higher"`
	SharesLower  int64              `json:"shares_lower"`
	Status       MarketStatus       `json:"status"`
	Outcome      NullMarketOutcome  `json:"outcome"`
	ClosesAt     pgtype.Timestamptz `json:"closes_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Position struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	MarketID     uuid.UUID          `json:"market_id"`
	SharesHigher int64              `json:"shares_higher"`
	SharesLower  int64              `json:"shares_lower"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Trade struct {
	ID                 uuid.UUID          `json:"id"`
	MarketID           uuid.UUID          `json:"market_id"`
	UserID             uuid.UUID          `json:"user_id"`
	Outcome            MarketOutcome      `json:"outcome"`
	Shares             int64              `json:"shares"`
	Cost               int64              `json:"cost"`
	SharesHigherBefore int64              `json:"shares_higher_before"`
	SharesLowerBefore  int64              `json:"shares_lower_before"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     string             `json:"password_hash"`
	Role             UserRole           `json:"role"`
	EmailVerified    bool               `json:"email_verified"`
	EmailVerifyToken *string            `json:"email_verify_token"`
	DisplayName      *string            `json:"display_name"`
	AvatarUrl        *string            `json:"avatar_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
