// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMarket(ctx context.Context, arg CreateMarketParams) (Market, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMarket(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetMarketByID(ctx context.Context, id uuid.UUID) (Market, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByVerifyToken(ctx context.Context, emailVerifyToken *string) (User, error)
	ListMarkets(ctx context.Context) ([]Market, error)
	ListMarketsByCourse(ctx context.Context, courseCode string) ([]Market, error)
	ListMarketsByCreator(ctx context.Context, creatorID uuid.UUID) ([]Market, error)
	ListMarketsByStatus(ctx context.Context, status MarketStatus) ([]Market, error)
	ListOpenMarkets(ctx context.Context) ([]Market, error)
	ListUsers(ctx context.Context) ([]User, error)
	ResolveMarket(ctx context.Context, arg ResolveMarketParams) (Market, error)
	SetEmailVerified(ctx context.Context, id uuid.UUID) (User, error)
	SetEmailVerifyToken(ctx context.Context, arg SetEmailVerifyTokenParams) (User, error)
	UpdateMarketShares(ctx context.Context, arg UpdateMarketSharesParams) (Market, error)
	UpdateMarketStatus(ctx context.Context, arg UpdateMarketStatusParams) (Market, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
