/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type OutcomeResultType = "NO" | "YES";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TradeType = "BUY" | "SELL";

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface GooseDbVersion {
  id: Generated<number>;
  is_applied: boolean;
  tstamp: Generated<Timestamp>;
  version_id: Int8;
}

export interface Markets {
  closes_at: Timestamp;
  course_code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  liquidity: Generated<Int8>;
  no_shares: Generated<Numeric>;
  outcome: OutcomeResultType | null;
  question: string;
  resolved: Generated<boolean>;
  semester: string;
  updated_at: Generated<Timestamp>;
  yes_shares: Generated<Numeric>;
}

export interface MarketSnapshots {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  market_id: number;
  no_price_cents: Int8;
  no_shares: Numeric;
  yes_price_cents: Int8;
  yes_shares: Numeric;
}

export interface Positions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  market_id: number;
  outcome: OutcomeResultType;
  shares: Numeric;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Session {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Trades {
  amount_cents: Int8;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  market_id: number;
  outcome: OutcomeResultType;
  shares: Numeric;
  trade_type: TradeType;
  user_id: string;
}

export interface User {
  balance_cents: Generated<Int8>;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp | null>;
  value: string;
}

export interface DB {
  account: Account;
  goose_db_version: GooseDbVersion;
  market_snapshots: MarketSnapshots;
  markets: Markets;
  positions: Positions;
  session: Session;
  trades: Trades;
  user: User;
  verification: Verification;
}
